"""Filesystem layout for the enrichment layer.

Everything the layer writes lives under ``data/`` at the repo root, which
is already gitignored upstream, so a 2.25 GB snapshot and a multi-GB
sidecar never risk being committed. Override the root with
``ATS_ENRICH_DATA_DIR`` to keep the working set on an external volume.
"""

from __future__ import annotations

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _data_root() -> Path:
    configured = os.environ.get("ATS_ENRICH_DATA_DIR")
    return Path(configured).expanduser() if configured else REPO_ROOT / "data"


DATA_DIR = _data_root()

#: The published full snapshot, downloaded once.
DEFAULT_SNAPSHOT = DATA_DIR / "all.parquet"

#: Sidecar store: enrichment rows, LLM cache, batch checkpoints, ledger.
DEFAULT_DB = DATA_DIR / "enrichment.duckdb"

#: Phase 0 / eval reports.
REPORT_DIR = DATA_DIR / "reports"

#: Batch API request/response shards.
BATCH_DIR = DATA_DIR / "batches"

#: Final joined output.
DEFAULT_OUTPUT = DATA_DIR / "all_enriched.parquet"

#: Snapshot manifest URL. Public, no auth.
MANIFEST_URL = "https://storage.stapply.ai/jobhive/v1/manifest.json"


def ensure_dirs() -> None:
    for path in (DATA_DIR, REPORT_DIR, BATCH_DIR):
        path.mkdir(parents=True, exist_ok=True)
    _self_ignore(DATA_DIR)


def _self_ignore(directory: Path) -> None:
    """Make the data directory exclude its own contents from git.

    Upstream's ``.gitignore`` covers ``*.parquet``, which is not enough: this
    layer also writes a multi-GB DuckDB store, batch shards, and join spill
    files, and ``git status`` was offering all 5.6 GB of it as untracked. A
    directory-local ignore keeps that out of a commit without editing the
    upstream ``.gitignore``, so pulls stay conflict-free, and it applies just
    as well when ``ATS_ENRICH_DATA_DIR`` points somewhere else.
    """
    marker = directory / ".gitignore"
    if not marker.exists():
        marker.write_text("# Generated by enrich/. Everything here is derived data.\n*\n")
